- hosts: appserver
  remote_user: root
  tasks:
  - name: Install new package git_CLI
    apt: name=git state=present

  - name: Install new package Nginx
    apt: name=nginx state=present

  - name: start the Nginx Service
    service: name=nginx state=started
  
  - name: Clone the source code from from git
    shell: "cd /var/www/html; git clone https://github.com/hariharanjenkin/webapp.git"

  - name: Deploy the web App
    shell: "cd /var/www/html/webapp; cp index.html /var/www/html"